### ISSUE TITLE
Feature Request: font sizing, and bug: height won't adjust panel

### ISSUE THREAD

**Issue by innkeeper9** [inbasic/bookmarks-manager#22]
I don't know if anyone else would actually want to size the font in the panel, but if it isn't hard to add that I would really like the option to adjust the font size of the bookmarks in the panel.

The panel width will adjust, but the height will not adjust beyond 600px in length.

**Comment by inbasic** [comment]
From the next release it is possible to open the panel in the sidebar (if your browser supports this [FF, and Opera at the moment]). In this view the height is 100% of the view port.

> will not adjust beyond 600px in length.

This is your browser limitation. There is no workaround for it.

> I don't know if anyone else would actually want to size the font in the panel

Go to the options page and add the following CCS rule to the styling section
```css
body {
  font-size: 16px
}
```

**Comment by inbasic** [comment]
If you are using Chrome, from the next release you can use the panel -> tools -> open in new page option to open the panel in a browser tab.
