### ISSUE TITLE
Feature request: Support for live bookmarks

### ISSUE THREAD

**Issue by mario98** [inbasic/bookmarks-manager#25]
Is support for live bookmarks planned?

There was a little but very popular addon called LiveClick which improved Firefox live bookmark appearance. It was awesome, see here: https://addons.cdn.mozilla.net/user-media/previews/full/54/54655.png
You could view all your feeds in a simple popup menu. Unfortunately, since Quantum this addon stopped working. No good alternative with the same GUI simplicity exists. All other RSS addons have their RSS feeds in a separate tab, which I consider bad GUI design since you have to open a separate tab then just to see if a new article is available.

This addon could have the potential to be a replacement for LiveClick if you added support for live bookmarks. At the moment live bookmarks are just shown as empty folders. But if you also support showing the entries, highlight feeds with new articles, show the number of unread articles etc. just as LiveClick, your addon would actually add some functionality not present in the Firefox default bookmark view and this would attract a lot of users who used LiveClick in the past.

**Comment by starlyte** [comment]
It is another action this addon could replace, hope so, it is useful and lacking.

**Comment by inbasic** [comment]
The support for RSS feed reading is added to the latest release. Read FAQ 10 for more info; https://add0n.com/bookmarks-manager.html
