### ISSUE TITLE
feature request: sortable results by Address column

### ISSUE THREAD

**Issue by Onetimeposter** [inbasic/bookmarks-manager#3]
On the result pane (after a serach term has been processed) allow the possibility to sort by URL (address)
Thx.

**Comment by csengh** [comment]
to close all request without any comment is not an option . . .

**Comment by inbasic** [comment]
This is implemented.

**Comment by taa1** [comment]
I can't figure out how to do this in the latest version I'm running, 0.2.4. Clicking on the "Address" column header doesn't seem to do anything. It would be nice if clicking on the "Title" column header were also possible.
