### ISSUE TITLE
Typing very fast into search returns invalid reults

### ISSUE THREAD

**Issue by davidjade** [inbasic/bookmarks-manager#34]
If I type very fast into the search box, this add-on returns more results than it should. If I type more slowly, then if returns the proper results. If I just type the last character after a pause, then it seems to work out but if I blast it all out in one go, then it returns invalid results. Seems like something is dropping characters if you type too fast.

**Comment by inbasic** [comment]
Thanks for the report. Please reopen if it is not fixed by the next release.
