### ISSUE TITLE
Request: default keyboard focus to search box when opening popup

### ISSUE THREAD

**Issue by davidjade** [inbasic/bookmarks-manager#35]
Please make it so that when the add-on is opened, it defaults the keyboard focus to the search box so that I can start typing right away without having to use the mouse to change the focus.

**Comment by inbasic** [comment]
> without having to use the mouse to change the focus.

alternative to the new option, you can use Ctrl + F to focus the search box too.

**Comment by davidjade** [comment]
This doesn’t work for me. Ctrl-F just opens the in page search option. Plus that is still one more extra keystroke even if it worked.
