### ISSUE TITLE
The "Tools" and "Bookmarks" drop down menus are broken

### ISSUE THREAD

**Issue by davidhedlund** [inbasic/bookmarks-manager#4]
I cannot access the options in "Tools" and "Bookmarks" menus, the options disappear when I try to select them.

I tried this in:

* Bookmarks Manager and Viewer version: 0.1.4
* Firefox version: Firefox ESR 52.3.0 (64-bit) binaries for GNU/Linux

**Comment by davidhedlund** [comment]
I tried this in:

* Bookmarks Manager and Viewer version: 0.1.4
* Firefox version: Firefox ESR 52.3.0 (64-bit) binaries for GNU/Linux

**Comment by inbasic** [comment]
Seems like the API is not available on 52. It works as expected in FF 55.

**Comment by davidhedlund** [comment]
@inbasic Thank you for verifying.
