### ISSUE TITLE
bugzilla reference to AMO

### ISSUE THREAD

**Issue by davidhedlund** [inbasic/bookmarks-manager#5]
I wrote this review: https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager-and-viewer/reviews/913694/

Can you please mention https://bugzilla.mozilla.org/show_bug.cgi?id=469441#c17 on https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager-and-viewer/ ?

**Comment by davidhedlund** [comment]
As I mentioned here: https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager-and-viewer/reviews/913694/

**Comment by inbasic** [comment]
done!

**Comment by davidhedlund** [comment]
@inbasic Thanks.
