### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by davidhedlund** [inbasic/bookmarks-manager#6]
I'm working as a volunteer for the Free Software Directory. Your program
is free software so in principle it should be listed there, and I'd like to
add it.  But it has some problems in showing what its license is.
Would you please fix them, for the sake of users and other developers?

Once your version with fixed license issues is public available on https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager-and-viewer/ we will review it, and if it meet our requirement I will approve http://directory.fsf.org/wiki/Bookmarks_Manager_and_Viewer. Once approved it will be listed on the official GNU IceCat add-on list at https://directory.fsf.org/wiki/IceCat. GNU IceCat is the GNU variant of Firefox.

See https://addons.mozilla.org/en-US/firefox/addon/librejs/ if you want to study a well licensed add-on.

# Issues

## No full copy of the license file included

There are no full copy of the license file

The root directory don't have a COPYING file with a copy of the software license. A plain text version of MPL 2.0 
can be found here: http://www.mozilla.org/MPL/2.0/ (https://www.mozilla.org/media/MPL/2.0/index.txt)

## Lack of full license headers in each file

There are no (full) license notices in the non-trivial source files

The source files in Bookmarks Manager and Viewer don't have notices saying you are the copyright
holder and/or that they are released under MPL 2.0. 
I'm writing to ask you to please put a notice on each nontrivial source file.

Selecting a license on a website that hosts the add-on (like addons.mozilla.org), will only show it there, the source files won't be modified.

First, here's why license notices are needed.

The purpose of a license notice is to state formally that a certain
file may be used under the terms of a particular license.

The MPL, like most free software licenses, applies to whatever
material is released under that license.  It does not say anything
about which programs are released that way.

Therefore, simply including a copy of the MPL with some code
does not release the code under the terms of the MPL.
To do that, you need a license notice, which says, more or less,
"We the copyright holders release this code under the MPL."

The source files should be accompanied by a copyright notice, which says who
"we" copyright holders are.  That takes the form "Copyright YEAR NAME".

For the MPL, there are two other reasons for a license notice: to say
which version of the MPL applies, and (for LICENSE 2.0), to say whether the
MPL's option of GPL compatibility applies.  It is enabled by default
in MPL 2.0, but users should have an explicit statement of where things
stand for any particular code.  The license notice is where you
specify this.

Why should the license notice be on _each_ source file?
Because doing it at the package level is error-prone.

In the free software community, it is not unusual to copy a file from
a free program into some other context.  If the source file doesn't
have its own license notice, then its licensing comes from the
original context.  In the other context, its licensing may not be
clear.  It may not be stated at all, or it could be stated wrong.  For
instance, what if the other program says, "This program is released
under Apache 2.0", or "This program is released under GNU GPL, version
3 or any later version published by the Free Software Foundation."

The result would be to misinform users about the file's licensing.

People sometimes copy part of a file, too.  If the file has a license
notice, people know to preserve that notice when copying part of the
file's code.  Otherwise, the licensing will probably get lost.

A different problem can happen if you copy code _into_ Bookmarks Manager and Viewer from
some other package.  Your package-level license notice would say it is
under MPL 2.0, but what if it actually carries some other license,
such as Apache 2.0, or GPL Version 3 or later?

Keeping a license notice in each file is the way to reliably show
users what their rights are.  Please don't let uncertainty creep in.

You've made a decision about the license -- would you please announce
it in a way that won't get forgotten?

Other people can use your work with bad intentions, even if the mistake were honestly
unintentional. That is why, unfortunately, we have to take lots of time with verifying
the legality of everything.

See https://www.gnu.org/licenses/gpl-howto.en.html for how to apply license notices.

# Licenseutils
* sudo apt-get install licenseutils
* Licenseutils [0.0.8 can edit .js](https://savannah.nongnu.org/bugs/index.php?49441#comment24) files (see [patch](http://git.savannah.gnu.org/cgit/licenseutils.git/commit/?id=0d365160cc0fb6d0ed5eb26cf6e762278867e653)). If you use a earlier version you need to temporary rename your .js files to .cpp (Javascript comments are the same as c++) until JS have been implemented (see [fix](https://savannah.nongnu.org/bugs/?49441)) and then rename them back to .js.
* Run this but with your name/copyright year/license: licensing notice -c 'Yoyodyne,\ Inc.\ 2001' -l gpl -s c -n *.cpp

# References
These issues are compatible with the policy listed in [Free Software Directory, Requirements](https://directory.fsf.org/wiki?title=Free_Software_Directory:Requirements).

**Comment by inbasic** [comment]
I think this is addressed. If not let me know!

**Comment by davidhedlund** [comment]
Please add this to your release notes.

**Comment by davidhedlund** [comment]
@inbasic Everything is fine.

**Comment by davidhedlund** [comment]
Previously I recommended a modification of the GPL guidelines which was wrong. Now I've had a fresh look on the actual license.

From https://www.mozilla.org/en-US/MPL/2.0/

Exhibit A - Source Code Form License Notice

> This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.

If it is not possible or desirable to put the notice in a particular file, then You may include the notice in a location (such as a LICENSE file in a relevant directory) where a recipient would be likely to look for such a notice.

You may add additional accurate notices of copyright ownership.


* Can you please download https://www.mozilla.org/media/MPL/2.0/index.txt, rename the file from index.txt to LICENSE, and put it in the root directory for your add-on?

* You can copy pre-defined headers from https://www.mozilla.org/en-US/MPL/headers/ if you want to use them.

**Comment by davidhedlund** [comment]
I updated the issue.

**Comment by inbasic** [comment]
COPYING is renamed to LICENSE

**Comment by davidhedlund** [comment]
@inbasic Thank you.

And now

```
/*******************************************************************************
    Bookmark Manager and Viewer - An elegant bookmark manager with fuzzy search and more

    Copyright (C) 2014-2017 InBasic

    This program is free software: you can redistribute it and/or modify
    it under the terms of the Mozilla Public License as published by
    the Mozilla Foundation, either version 2 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    Mozilla Public License for more details.
    You should have received a copy of the Mozilla Public License
    along with this program.  If not, see {https://www.mozilla.org/en-US/MPL/}.

    Home: http://add0n.com/bookmarks-manager.html
    GitHub: https://github.com/inbasic/bookmarks-manager/
*/
```

with


```
/* Copyright (C) 2014-2017 InBasic
 * 
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 * 
 * Home: http://add0n.com/bookmarks-manager.html
 * GitHub: https://github.com/inbasic/bookmarks-manager/
*/
```

**Comment by inbasic** [comment]
done!

**Comment by davidhedlund** [comment]
@inbasic Thank you once again.

**Comment by davidhedlund** [comment]
Please read https://github.com/mozilla/addons-server/issues/6318#issuecomment-327697059 and vote on the comment to help us on the Free Software Directory speed up the license approval process.
