### ISSUE TITLE
Please add GitHub link to AMO

### ISSUE THREAD

**Issue by davidhedlund** [inbasic/bookmarks-manager#7]
Can you please add https://github.com/inbasic/bookmarks-manager/ to https://addons.mozilla.org/en-US/firefox/addon/bookmarks-manager-and-viewer/ ?

**Comment by inbasic** [comment]
We already have the link in the description
```
For bug reports use:
https://github.com/inbasic/bookmarks-manager
```

**Comment by davidhedlund** [comment]
@inbasic Sorry if I missed that.
